In [70]:
import pandas as pd
import ast

In [71]:
df=pd.read_json(r"C:\Users\Hp\OneDrive\Desktop/airbnb.py/sample_airbnb.json")

In [72]:

df['review_scores']= df["review_scores"].apply(lambda x: x.get("review_scores_rating",0))

In [73]:
df['review_scores']

0        94
1        92
2       100
3        92
4        95
       ...
5550      0
5551     92
5552     85
5553      0
5554      0
Name: review_scores, Length: 5555, dtype: int64

In [74]:
df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",94,"[{'_id': '4351675', 'date': '2013-04-29 04:00:...",NaN,NaN,NaN
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '52004703', 'host_url': 'https://w...","{'street': 'Fatih , İstanbul, Turkey', 'suburb...","{'availability_30': 30, 'availability_60': 60,...",92,"[{'_id': '149469150', 'date': '2017-05-04 04:0...",NaN,NaN,NaN
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51624384', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 0, 'availability_60': 0, '...",100,"[{'_id': '56904633', 'date': '2015-12-19 05:00...",5000.0,NaN,NaN
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51744313', 'host_url': 'https://w...","{'street': 'Hong Kong , 九龍, Hong Kong', 'subur...","{'availability_30': 14, 'availability_60': 24,...",92,"[{'_id': '57191745', 'date': '2015-12-22 05:00...",1350.0,5000.0,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '13764143', 'host_url': 'https://w...","{'street': 'Surry Hills, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",95,"[{'_id': '123549502', 'date': '2016-12-29 05:0...",NaN,NaN,NaN

In [75]:
df1=pd.read_csv(r"C:/Users/Hp/OneDrive/Desktop/airbnb.py/sample_airbnb.csv")

In [76]:
df1

,Unnamed: 0,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,NaN,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",...,1,https://a0.muscache.com/im/pictures/15074036/a...,"{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",94,"[{'_id': '4351675', 'date': '2013-04-29 04:00:...",NaN,NaN,NaN
1,1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,NaN,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,NaN,Tram 5 minutes metro 10 minutes Bus 10 minutes,...,1,https://a0.muscache.com/im/pictures/68de30b5-e...,"{'host_id': '52004703', 'host_url': 'https://w...","{'street': 'Fatih , İstanbul, Turkey', 'suburb...","{'availability_30': 30, 'availability_60': 60,...",92,"[{'_id': '149469150', 'date': '2017-05-04 04:0...",NaN,NaN,NaN
2,2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,"Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/4533a1dc-6...,"{'host_id': '51624384', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 0, 'availability_60': 0, '...",100,"[{'_id': '56904633', 'date': '2015-12-19 05:00...",5000.0,NaN,NaN
3,3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...",...,1,https://a0.muscache.com/im/pictures/e6275515-7...,"{'host_id': '51744313', 'host_url': 'https://w...","{'street': 'Hong Kong , 九龍, Hong Kong', 'subur...","{'availability_30': 14, 'availability_60': 24,...",92,"[{'_id': '57191745', 'date': '2015-12-22 05:00...",1350.0,5000.0,NaN
4,4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,...,1,https://a0.muscache.com/im/pictures/f8eaba4e-d...,"{'host_id': '13764143', 'host_url': 'https://w...","{'street': 'Surry Hills, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",95,"[{'_id': '123549502', 'date': '2016-12-29 05:0...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/e40d18b2-1...,"{'host_id': '51303748', 'host_url': 'https://w...","{'street': 'Kadıköy, İstanbul, Turkey', 'subur...","{'availability_30': 30, 'availability_60': 60,...",0,[],NaN,NaN,NaN
5551,5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,...,1,https://a0.muscache.com/im/pictures/be1978c5-6...,"{'host_id': '51013381', 'host_url': 'https://w...","{'street': 'Lahaina, HI, United States', 'subu...","{'availability_30': 0, 'availability_60': 8, '...",92,"[{'_id': '68762225', 'date': '2016-04-06 04:00...",NaN,NaN,NaN
5552,5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Newly renovated studio flat with full furniture.,NaN,Newly renovated studio flat with full furniture.,NaN,NaN,NaN,...,2,https://a0.muscache.com/im/pictures/a39e3f36-9...,"{'host_id': '31386255', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 18, 'availability_60': 48,...",85,"[{'_id': '105800033', 'date': '2016-10-02 04:0...",NaN,NaN,NaN
5553,5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,NaN,A bright large double room is available in a b...,NaN,NaN,The flat is exactly half way between the shops...,...,2,https://a0.muscache.com/im/pictures/17a8857a-6...,"{'host_id': '47615848', 'host_url': 'https://w...","{'street': 'Bondi Beach, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",0,[],NaN,NaN,NaN
5554,5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/9d939095-f...,"{'host_id': '47092481', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 0, 'availability_60': 0, '...",0,[],NaN,NaN,NaN

In [77]:
Dataframe=df1.drop('Unnamed: 0',axis=1,inplace=False)

In [78]:
Dataframe

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,NaN,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,1,https://a0.muscache.com/im/pictures/15074036/a...,"{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",94,"[{'_id': '4351675', 'date': '2013-04-29 04:00:...",NaN,NaN,NaN
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,NaN,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,NaN,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,1,https://a0.muscache.com/im/pictures/68de30b5-e...,"{'host_id': '52004703', 'host_url': 'https://w...","{'street': 'Fatih , İstanbul, Turkey', 'suburb...","{'availability_30': 30, 'availability_60': 60,...",92,"[{'_id': '149469150', 'date': '2017-05-04 04:0...",NaN,NaN,NaN
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,"Clean, fully furnish, Spacious 1 bedroom flat ...",NaN,NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/4533a1dc-6...,"{'host_id': '51624384', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 0, 'availability_60': 0, '...",100,"[{'_id': '56904633', 'date': '2015-12-19 05:00...",5000.0,NaN,NaN
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,1,https://a0.muscache.com/im/pictures/e6275515-7...,"{'host_id': '51744313', 'host_url': 'https://w...","{'street': 'Hong Kong , 九龍, Hong Kong', 'subur...","{'availability_30': 14, 'availability_60': 24,...",92,"[{'_id': '57191745', 'date': '2015-12-22 05:00...",1350.0,5000.0,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,1,https://a0.muscache.com/im/pictures/f8eaba4e-d...,"{'host_id': '13764143', 'host_url': 'https://w...","{'street': 'Surry Hills, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",95,"[{'_id': '123549502', 'date': '2016-12-29 05:0...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/e40d18b2-1...,"{'host_id': '51303748', 'host_url': 'https://w...","{'street': 'Kadıköy, İstanbul, Turkey', 'subur...","{'availability_30': 30, 'availability_60': 60,...",0,[],NaN,NaN,NaN
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,Guests will have access to the 3 pools in the ...,...,1,https://a0.muscache.com/im/pictures/be1978c5-6...,"{'host_id': '51013381', 'host_url': 'https://w...","{'street': 'Lahaina, HI, United States', 'subu...","{'availability_30': 0, 'availability_60': 8, '...",92,"[{'_id': '68762225', 'date': '2016-04-06 04:00...",NaN,NaN,NaN
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Newly renovated studio flat with full furniture.,NaN,Newly renovated studio flat with full furniture.,NaN,NaN,NaN,NaN,...,2,https://a0.muscache.com/im/pictures/a39e3f36-9...,"{'host_id': '31386255', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 18, 'availability_60': 48,...",85,"[{'_id': '105800033', 'date': '2016-10-02 04:0...",NaN,NaN,NaN
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,NaN,A bright large double room is available in a b...,NaN,NaN,The flat is exactly half way between the shops...,"Guests will have access to the full residence,...",...,2,https://a0.muscache.com/im/pictures/17a8857a-6...,"{'host_id': '47615848', 'host_url': 'https://w...","{'street': 'Bondi Beach, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",0,[],NaN,NaN,NaN
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,Apartamento amplo que acomoda 6 pessoas. Um qu...,NaN,NaN,NaN,NaN,...,1,https://a0.muscache.com/im/pictures/9d939095-f...,"{'host_id': '47092481', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 0, 'availability_60': 0, '...",0,[],NaN,NaN,NaN

In [79]:
Dataframe.isnull().sum()

_id                         0
listing_url                 0
name                        8
summary                   258
space                    1626
description                95
neighborhood_overview    2241
notes                    3081
transit                  2232
access                   2453
interaction              2478
house_rules              2285
property_type               0
room_type                   0
bed_type                    0
minimum_nights              0
maximum_nights              0
cancellation_policy         0
last_scraped                0
calendar_last_scraped       0
first_review             1388
last_review              1388
accommodates                0
bedrooms                    5
beds                       13
number_of_reviews           0
bathrooms                  10
amenities                   0
price                       0
security_deposit         2084
cleaning_fee             1531
extra_people                0
guests_included             0
images                      0
host                        0
address                     0
availability                0
review_scores               0
reviews                     0
weekly_price             4841
monthly_price            4899
reviews_per_month        5461
dtype: int64

In [80]:
Dataframe.isnull().sum()

_id                         0
listing_url                 0
name                        8
summary                   258
space                    1626
description                95
neighborhood_overview    2241
notes                    3081
transit                  2232
access                   2453
interaction              2478
house_rules              2285
property_type               0
room_type                   0
bed_type                    0
minimum_nights              0
maximum_nights              0
cancellation_policy         0
last_scraped                0
calendar_last_scraped       0
first_review             1388
last_review              1388
accommodates                0
bedrooms                    5
beds                       13
number_of_reviews           0
bathrooms                  10
amenities                   0
price                       0
security_deposit         2084
cleaning_fee             1531
extra_people                0
guests_included             0
images                      0
host                        0
address                     0
availability                0
review_scores               0
reviews                     0
weekly_price             4841
monthly_price            4899
reviews_per_month        5461
dtype: int64

In [81]:
Dataframe.fillna(0,inplace=True)

In [82]:
Dataframe.isnull().sum()

_id                      0
listing_url              0
name                     0
summary                  0
space                    0
description              0
neighborhood_overview    0
notes                    0
transit                  0
access                   0
interaction              0
house_rules              0
property_type            0
room_type                0
bed_type                 0
minimum_nights           0
maximum_nights           0
cancellation_policy      0
last_scraped             0
calendar_last_scraped    0
first_review             0
last_review              0
accommodates             0
bedrooms                 0
beds                     0
number_of_reviews        0
bathrooms                0
amenities                0
price                    0
security_deposit         0
cleaning_fee             0
extra_people             0
guests_included          0
images                   0
host                     0
address                  0
availability             0
review_scores            0
reviews                  0
weekly_price             0
monthly_price            0
reviews_per_month        0
dtype: int64

In [83]:
Dataframe.dtypes

_id                        int64
listing_url               object
name                      object
summary                   object
space                     object
description               object
neighborhood_overview     object
notes                     object
transit                   object
access                    object
interaction               object
house_rules               object
property_type             object
room_type                 object
bed_type                  object
minimum_nights             int64
maximum_nights             int64
cancellation_policy       object
last_scraped              object
calendar_last_scraped     object
first_review              object
last_review               object
accommodates               int64
bedrooms                 float64
beds                     float64
number_of_reviews          int64
bathrooms                float64
amenities                 object
price                      int64
security_deposit         float64
cleaning_fee             float64
extra_people               int64
guests_included            int64
images                    object
host                      object
address                   object
availability              object
review_scores              int64
reviews                   object
weekly_price             float64
monthly_price            float64
reviews_per_month        float64
dtype: object

In [84]:
df.keys()

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'host', 'address',
       'availability', 'review_scores', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month'],
      dtype='object')

In [85]:
host_df = Dataframe[['_id','host']]

In [86]:
host_df

           _id                                               host
0      1003530  {'host_id': '454250', 'host_url': 'https://www...
1     10133554  {'host_id': '52004703', 'host_url': 'https://w...
2     10059872  {'host_id': '51624384', 'host_url': 'https://w...
3     10084023  {'host_id': '51744313', 'host_url': 'https://w...
4     10091713  {'host_id': '13764143', 'host_url': 'https://w...
...        ...                                                ...
5550   9985696  {'host_id': '51303748', 'host_url': 'https://w...
5551   9993190  {'host_id': '51013381', 'host_url': 'https://w...
5552   9887054  {'host_id': '31386255', 'host_url': 'https://w...
5553   9907907  {'host_id': '47615848', 'host_url': 'https://w...
5554   9936016  {'host_id': '47092481', 'host_url': 'https://w...

[5555 rows x 2 columns]

In [87]:


host_df['host'] = host_df['host'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

C:\Users\Hp\AppData\Local\Temp\ipykernel_20284\145076023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  host_df['host'] = host_df['host'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [88]:
host_columns= {'_id':[],'host_id':[], 'host_url':[], 'host_name':[], 'host_location':[],"host_response_time":[], 'host_thumbnail_url':[], 'host_picture_url':[], 'host_neighbourhood':[], 'host_response_rate':[], 'host_is_superhost':[], 'host_has_profile_pic':[], 'host_identity_verified':[], 'host_listings_count':[], 'host_total_listings_count':[], 'host_verifications':[]}

for i in host_df["_id"]:
    host_columns["_id"].append(i)
for i in host_df["host"]:
    host_columns["host_id"].append(i["host_id"])
    host_columns["host_url"].append(i["host_url"])
    host_columns["host_name"].append(i["host_name"])
    host_columns["host_location"].append(i["host_location"])
    host_columns["host_response_time"].append(i.get("host_response_time"))
    host_columns["host_thumbnail_url"].append(i["host_thumbnail_url"])
    host_columns["host_picture_url"].append(i["host_picture_url"])
    host_columns["host_neighbourhood"].append(i["host_neighbourhood"])
    host_columns["host_response_rate"].append(i.get("host_response_rate"))
    host_columns["host_is_superhost"].append(i["host_is_superhost"])
    host_columns["host_has_profile_pic"].append(i["host_has_profile_pic"])
    host_columns["host_identity_verified"].append(i["host_identity_verified"])
    host_columns["host_listings_count"].append(i["host_listings_count"])
    host_columns["host_total_listings_count"].append(i["host_total_listings_count"])
    host_columns["host_verifications"].append(i["host_verifications"])

In [89]:
host_data=pd.DataFrame(host_columns)

In [90]:
host_data.isnull().sum()

_id                             0
host_id                         0
host_url                        0
host_name                       0
host_location                   0
host_response_time           1388
host_thumbnail_url              0
host_picture_url                0
host_neighbourhood              0
host_response_rate           1388
host_is_superhost               0
host_has_profile_pic            0
host_identity_verified          0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
dtype: int64

In [91]:
host_data.fillna(0,inplace=True)

In [92]:
host_data.isnull().sum()

_id                          0
host_id                      0
host_url                     0
host_name                    0
host_location                0
host_response_time           0
host_thumbnail_url           0
host_picture_url             0
host_neighbourhood           0
host_response_rate           0
host_is_superhost            0
host_has_profile_pic         0
host_identity_verified       0
host_listings_count          0
host_total_listings_count    0
host_verifications           0
dtype: int64

In [93]:
Address_df=Dataframe[["_id","address"]]

In [94]:
Address_df

           _id                                            address
0      1003530  {'street': 'New York, NY, United States', 'sub...
1     10133554  {'street': 'Fatih , İstanbul, Turkey', 'suburb...
2     10059872  {'street': 'Hong Kong, Hong Kong Island, Hong ...
3     10084023  {'street': 'Hong Kong , 九龍, Hong Kong', 'subur...
4     10091713  {'street': 'Surry Hills, NSW, Australia', 'sub...
...        ...                                                ...
5550   9985696  {'street': 'Kadıköy, İstanbul, Turkey', 'subur...
5551   9993190  {'street': 'Lahaina, HI, United States', 'subu...
5552   9887054  {'street': 'Hong Kong, Hong Kong Island, Hong ...
5553   9907907  {'street': 'Bondi Beach, NSW, Australia', 'sub...
5554   9936016  {'street': 'Rio de Janeiro, Rio de Janeiro, Br...

[5555 rows x 2 columns]

In [95]:
Address_df['address'] = Address_df['address'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

C:\Users\Hp\AppData\Local\Temp\ipykernel_20284\2771251030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Address_df['address'] = Address_df['address'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [96]:
address_columns= {'_id':[], 'street':[], 'suburb':[], 'government_area':[], 'market':[], 'country':[],
                   'country_code':[], 'location_type':[], "longitude":[], "latitude":[],
                    "is_location_exact":[]}

for i in Address_df["_id"]:
    address_columns["_id"].append(i)

for i in Address_df["address"]:
    address_columns["street"].append(i["street"])
    address_columns["suburb"].append(i["suburb"])
    address_columns["government_area"].append(i["government_area"])
    address_columns["market"].append(i["market"])
    address_columns["country"].append(i["country"])
    address_columns["country_code"].append(i["country_code"])
    address_columns["location_type"].append(i["location"]["type"])
    address_columns["longitude"].append(i["location"]["coordinates"][0])
    address_columns["latitude"].append(i["location"]["coordinates"][1])
    address_columns["is_location_exact"].append(i["location"]["is_location_exact"])

In [97]:
Address_data=pd.DataFrame(address_columns)

In [98]:
Address_data

,_id,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact
0,1003530,"New York, NY, United States",Manhattan,Upper West Side,New York,United States,US,Point,-73.965230,40.799620,False
1,10133554,"Fatih , İstanbul, Turkey",Fatih,Fatih,Istanbul,Turkey,TR,Point,28.980090,41.006200,False
2,10059872,"Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.150270,22.281580,True
3,10084023,"Hong Kong , 九龍, Hong Kong",Sham Shui Po District,Sham Shui Po,Hong Kong,Hong Kong,HK,Point,114.166900,22.331400,True
4,10091713,"Surry Hills, NSW, Australia",Darlinghurst,Sydney,Sydney,Australia,AU,Point,151.215540,-33.880290,True
...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.030790,40.985630,False
5551,9993190,"Lahaina, HI, United States",Lahaina,Lahaina,Maui,United States,US,Point,-156.667520,20.858940,False
5552,9887054,"Hong Kong, Hong Kong Island, Hong Kong",Quarry Bay,Eastern,Hong Kong,Hong Kong,HK,Point,114.207220,22.291570,False
5553,9907907,"Bondi Beach, NSW, Australia",Bondi,Waverley,Sydney,Australia,AU,Point,151.265420,-33.892980,False
5554,9936016,"Rio de Janeiro, Rio de Janeiro, Brazil",Lapa,Centro,Rio De Janeiro,Brazil,BR,Point,-43.173761,-22.908336,False

In [99]:
Address_data.fillna("NA",inplace=True)

In [100]:

Address_data.isnull().sum()

_id                  0
street               0
suburb               0
government_area      0
market               0
country              0
country_code         0
location_type        0
longitude            0
latitude             0
is_location_exact    0
dtype: int64

In [101]:
Availability_df=Dataframe[["_id","availability"]]

In [102]:
Availability_df['availability'] =Availability_df['availability'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

C:\Users\Hp\AppData\Local\Temp\ipykernel_20284\1583540065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Availability_df['availability'] =Availability_df['availability'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [103]:
availabe_columns= {'_id':[], 'availability_30':[], 'availability_60':[], 'availability_90':[], 'availability_365':[]}

for i in Availability_df["_id"]:
    availabe_columns["_id"].append(i)

for i in Availability_df["availability"]:
    availabe_columns["availability_30"].append(i["availability_30"])
    availabe_columns["availability_60"].append(i["availability_60"])
    availabe_columns["availability_90"].append(i["availability_90"])
    availabe_columns["availability_365"].append(i["availability_365"])

In [104]:
Availablity_data=pd.DataFrame(availabe_columns)

In [105]:
Availablity_data

,_id,availability_30,availability_60,availability_90,availability_365
0,1003530,0,0,0,93
1,10133554,30,60,90,365
2,10059872,0,0,0,0
3,10084023,14,24,40,220
4,10091713,0,0,0,0
...,...,...,...,...,...
5550,9985696,30,60,90,365
5551,9993190,0,8,31,258
5552,9887054,18,48,78,353
5553,9907907,0,0,0,0
5554,9936016,0,0,0,0

In [106]:
Availablity_data.fillna("NA",inplace=True)

In [107]:
Dataframe.keys()

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'host', 'address',
       'availability', 'review_scores', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month'],
      dtype='object')

In [108]:
data_set=Dataframe[['_id','listing_url','name','property_type','room_type','bed_type','minimum_nights','maximum_nights','cancellation_policy','accommodates','bedrooms','beds','number_of_reviews','bathrooms','price','extra_people','guests_included','images','review_scores','cleaning_fee','amenities']]
merged_df = pd.merge(host_data, Address_data, on='_id', how='inner')
final_merged_df = pd.merge(merged_df, Availablity_data, on='_id', how='inner')
Airbnb_data=data_set.merge(final_merged_df)

In [109]:
data_set.keys()

Index(['_id', 'listing_url', 'name', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'price', 'extra_people', 'guests_included', 'images', 'review_scores',
       'cleaning_fee', 'amenities'],
      dtype='object')

In [110]:
Airbnb_data['review_scores']

0        94
1        92
2       100
3        92
4        95
       ...
5550      0
5551     92
5552     85
5553      0
5554      0
Name: review_scores, Length: 5555, dtype: int64

In [111]:
Airbnb_data.dtypes

_id                            int64
listing_url                   object
name                          object
property_type                 object
room_type                     object
bed_type                      object
minimum_nights                 int64
maximum_nights                 int64
cancellation_policy           object
accommodates                   int64
bedrooms                     float64
beds                         float64
number_of_reviews              int64
bathrooms                    float64
price                          int64
extra_people                   int64
guests_included                int64
images                        object
review_scores                  int64
cleaning_fee                 float64
amenities                     object
host_id                       object
host_url                      object
host_name                     object
host_location                 object
host_response_time            object
host_thumbnail_url            object
host_picture_url              object
host_neighbourhood            object
host_response_rate           float64
host_is_superhost               bool
host_has_profile_pic            bool
host_identity_verified          bool
host_listings_count            int64
host_total_listings_count      int64
host_verifications            object
street                        object
suburb                        object
government_area               object
market                        object
country                       object
country_code                  object
location_type                 object
longitude                    float64
latitude                     float64
is_location_exact               bool
availability_30                int64
availability_60                int64
availability_90                int64
availability_365               int64
dtype: object

In [112]:
Airbnb_data.fillna("Nan",inplace=True)

In [113]:
Airbnb_data.isnull().sum()

_id                          0
listing_url                  0
name                         0
property_type                0
room_type                    0
bed_type                     0
minimum_nights               0
maximum_nights               0
cancellation_policy          0
accommodates                 0
bedrooms                     0
beds                         0
number_of_reviews            0
bathrooms                    0
price                        0
extra_people                 0
guests_included              0
images                       0
review_scores                0
cleaning_fee                 0
amenities                    0
host_id                      0
host_url                     0
host_name                    0
host_location                0
host_response_time           0
host_thumbnail_url           0
host_picture_url             0
host_neighbourhood           0
host_response_rate           0
host_is_superhost            0
host_has_profile_pic         0
host_identity_verified       0
host_listings_count          0
host_total_listings_count    0
host_verifications           0
street                       0
suburb                       0
government_area              0
market                       0
country                      0
country_code                 0
location_type                0
longitude                    0
latitude                     0
is_location_exact            0
availability_30              0
availability_60              0
availability_90              0
availability_365             0
dtype: int64

In [123]:
a=Airbnb_data.to_csv("Airbnb.csv")

In [125]:
data=pd.read_csv(r"C:\Users\Hp\OneDrive\Desktop\airbnb.py\Airbnb.csv")

In [126]:
data['review_scores']

0        94
1        92
2       100
3        92
4        95
       ...
5550      0
5551     92
5552     85
5553      0
5554      0
Name: review_scores, Length: 5555, dtype: int64